[package]
name = "lcs-image-diff-js"
version = "0.1.0"
authors = ["bokuweb <bokuweb12@gmail.com>"]

[dependencies]
lcs-diff = "*"
serde_derive = "^1.0.21"
serde = "^1.0.21"
serde_json = "^1.0.6"
base64 = "*"